-- Criação do usuário
CREATE USER gs IDENTIFIED BY gs123;
GRANT CONNECT, RESOURCE TO gs;

-- Criação da tabela usada na API
CREATE TABLE gs.motos (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          modelo VARCHAR2(100),
                          ano NUMBER,
                          placa VARCHAR2(10)
);